all:
	g++ main.cpp chip.cpp Graphics.cpp -I "C:\Users\jyash\Downloads\SDL2-devel-2.30.12-mingw\SDL2-2.30.12\i686-w64-mingw32\include" -L "C:\Users\jyash\Downloads\SDL2-devel-2.30.12-mingw\SDL2-2.30.12\i686-w64-mingw32\lib" -lSDL2
